### ISSUE TITLE
Support optional parameters in routes.

### ISSUE THREAD

**Issue by petforsberg** [symfony-cmf/RoutingAutoBundle#110]
According to a SEO specialist I work with (and we want to build our CMS with use of CMF), there is a need to use parameters in routes, which are no routes themselves, but only used in controllers.

Normally, Routing-Auto-Bundle creates a routes built up from "path-unit", e.g.:
domnain.com/category/article
could correspond to /routes/cms/category/article Rout object.

With parameters however, there is a need to add some information to a controller in a way that was easily achieved in standard Symfony2 - when paramters are passed to a controller, e.g.:
domain.com/category/article/{page}

This is a basic example. But perhaps some might need also different cases, like:
domnain.com/{category}/article/{page}

where both category and page are just paramters - variables passed to a controller. (Is it possible in Content Repository based routes? I hope it is...).

Perhaps more sophisticated things are also possible? Example:

domain/category[-]{theme}/article[-p]{page}
i.e.
Route is: /routes/cms/category/article
And the pattern for a route is: domain/category-.../article-p...
"..." respond to a parameter, so finally in this case controller would get $theme and $page variables.

But at the moment the most important is the first case (the one with {page} at the end of an url), if the others are too complex.

**Comment by dantleech** [comment]
Opened #152 which is more to the point as this issue is quite long and confusing now.
