### ISSUE TITLE
Flexible creation path?

### ISSUE THREAD

**Issue by petforsberg** [symfony-cmf/RoutingAutoBundle#132]
Hi there again,

I'm trying to create a forum with use of Symfony CMF, and wonder if the RoutingAuto bundle would be helpful here, or am I forced to create routes manually for each created Forum-related document.

Forum needs three things: "a folder" (container for sub-forums), thread ("a folder" containing posts), and post. Since the first two are just containers, I created a single common Document for them - the only difference between both is the field "IsThread" set to true or false.

Now I wondered if paths for them could be created automatically. I can see that in RoutingAuto bundle the path is somewhat statical, e.g.:

    uri_schema: /forum/{subforum-container-name}

While the thing here is to be totally flexible here, and have ability to create theoretically infitite number of the depth level (i.e. one subforum-container can hold any number of related nested children subforum-containers), example:

    /routes/forum/entertainment/fantasy/sf/movies/users-own-custom-category/users-own-custom-subcategory/and-so-on

So, *is there any solution in the RoutingAuto to not depend on the base path*?

**Comment by eggyal** [comment]
+1

**Comment by WouterJ** [comment]
Closing in favor of https://github.com/symfony-cmf/RoutingAutoBundle/issues/136 , which had a discussion that led to a conclusion.
