### ISSUE TITLE
SF parameters recognition

### ISSUE THREAD

**Issue by petforsberg** [symfony-cmf/RoutingAutoBundle#137]
Just installed all (except Tree Browser) bundles to dev-master version. Hoped it will work with newest Routing Auto, but it doesn't...

From my config:

    uri_schema: /{category}/%relative_articles_path%/{title}

URL generated is:

    ..../category/%relative_articles_path%/title

not

    ..../category/articles/title

Route Auto bundle doesn't recognize SF global parameters. Hope that paths duplication is not aimed. :)

**Comment by WouterJ** [comment]
Closing as the token provider was added by https://github.com/symfony-cmf/RoutingAutoBundle/pull/153
