### ISSUE TITLE
AutoRouteManager doesn't re-translate objects back to current translation

### ISSUE THREAD

**Issue by jnssthl** [symfony-cmf/RoutingAutoBundle#145]
Hi,
The AutoRouteManager translates Documents onFlush to any available locale in order to generate their Uri:

`Line 101: $this->adapter->translateObject($uriContextCollection->getSubjectObject(), $locale);`

But does not translate them back to the translation they had right before they were persisted/flushed.
In my case this leads to that I need to translate my object back:

`$document = $dm->findTranslation(null, '/cms/document', 'de');`
`// => available locales: en, de`
`$document->setTitle('New title');`

`$dm = $this->get('doctrine_phpcr.odm.document_manager');`
`$dm->persist($page);`
`$dm->flush();`

`//  $document->getLocale() => 'en'`

Is this intended, or am I missing something? ;-)

Cheers

**Comment by WouterJ** [comment]
So, what has to be done here? Not knowing that much about the ODM, what "loading" are you talking about here? `DocumentManager#find()` ?

**Comment by dbu** [comment]
we talk about findTranslation. should be repeated with the orig locale after generating route. dm has a method to get current locale of doc if i am not mistaken

**Comment by WouterJ** [comment]
Hmm, I see no method like that at the moment (only `{bind|find|remove}Translation` and `getLocalesFor`).

**Comment by dbu** [comment]
indeed. the method is on the unit of work. its called getCurrentLocale.

now we have a couple of new challenges:

* AdapterInterface::translateObject assumes that the object itself can
be translated. imho this is not very flexible - some systems might need
to return a different object that represents the other language.
* we could add something to the interface to make this work (like record
translation and restore translation or something like that). what i
would prefer is declaring translateObject to return something and make
AutoRouteManager::getUriContextsForDocument use the return value. for
phpcr-odm, we could then record the locale of the document with
uow->getCurrentLocale, fetch the translation, clone the document and
then re-fetch the original language to set it back, then return the
clone. i see no simpler solution unfortunately - phpcr-odm currently has
no method to get a detached translation directly. if the
getCurrentLocale is the same as the requested, we can just return the
document.

wdyt?

**Comment by WouterJ** [comment]
@dbu I agree about the returning part, did that in https://github.com/symfony-cmf/RoutingAuto/pull/53

I've fixed the locale bug in the listener instead: https://github.com/symfony-cmf/RoutingAutoBundle/pull/159 I think this is a lot cleaner than cloning the document and such.

**Comment by dantleech** [comment]
I guess @WouterJ has now addressed both issues raised by @dbu.

**Comment by dbu** [comment]
yep, looks good. lets leave this open until #159 is merged.
