### ISSUE TITLE
Support multiple schemas per route

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/RoutingAutoBundle#156]
For example, you might want to have several URLs each time a document is saved.

For example:

````
/path/to/image
/path/to/image/thumbnail
````

Or

````
/path/to/document
/path/to/document/edit
/path/to/document/vote
````

Ideally it would be good to allow these individual URls to be redirect to a different controller, using the dynamic routers `_type` (?) key.

**Comment by dbu** [comment]
:+1:

**Comment by almacbe** [comment]
:+1:

**Comment by dantleech** [comment]
I made a preliminary start on this in: https://github.com/symfony-cmf/RoutingAuto/pull/48

**Comment by dantleech** [comment]
This is now working in PR #172, would be great if it could be tested.

**Comment by dantleech** [comment]
Done!
