### ISSUE TITLE
Composer versions error

### ISSUE THREAD

**Issue by gerfigna** [symfony-cmf/RoutingAutoBundle#178]
When i do 
composer require symfony-cmf/routing-auto-bundle

I get:
  Problem 1
    - symfony-cmf/routing-auto-bundle 1.0.2 requires symfony-cmf/routing-auto 1.0.* -> no matching package found.
    - symfony-cmf/routing-auto-bundle 1.0.1 requires symfony-cmf/routing-auto 1.0.* -> no matching package found.
    - symfony-cmf/routing-auto-bundle 1.0.0 requires symfony-cmf/routing-auto ~1.0 -> no matching package found.
    - Installation request for symfony-cmf/routing-auto-bundle ^1.0 -> satisfiable by symfony-cmf/routing-auto-bundle[1.0.0, 1.0.1, 1.0.2].

I have tested using a composer.json file with no dependences and i get the same error

**Comment by dantleech** [comment]
strange, our tags are not showing up in composer, @WouterJ any ideas?

**Comment by gerfigna** [comment]
I think the problem is on symfony-cmf/routing-auto version tags.

http://semver.mwl.be/#?package=symfony-cmf%2Frouting-auto&version=dev-master&minimum-stability=stable

**Comment by dantleech** [comment]
Looks like a composer glitch. I updated and the tags have come back,
thanks for the report :)

**Comment by gerfigna** [comment]
Now, version tags are OK. Thanks !

**Comment by almacbe** [comment]
@dantleech thanks ;-)
