### ISSUE TITLE
Cherry-pick the new Slugifier API DI config to 1.1

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/RoutingAutoBundle#179]
1.1 should use the "new"  Slugifier API package:

```
Symfony\Cmf\Api\Slugifier\CallbackSlugifier
```

**Comment by dbu** [comment]
also the composer.json needs to be adjusted

**Comment by dbu** [comment]
i just tagged 1.0.0 of the slugifier package. this seems the last blocker for the 1.1 release

**Comment by WouterJ** [comment]
Not sure what this meant, but afaics everything should be OK now.
