### ISSUE TITLE
Method to call Controllers and Templates based on class

### ISSUE THREAD

**Issue by awdng** [symfony-cmf/RoutingAutoBundle#66]
The DynamicRouter has the possibility to call different controllers and template by class or type, but for AutoRouting it doesn't work because the Route Documents are all of the same type. This doesn't seem to be documented so i wonder if its possible at all.

Of course this could be done in other ways, i was just wondering if there is a way to do it like DynamicRouter intends to.

**Comment by WouterJ** [comment]
So let's close this, as it turns out it is already possible. Only the `*_by_type` isn't possible, but we kinda agree that there isn't much usecase for this.
